-- EUComply Checklist Items Seed Data
-- Applied via Supabase MCP: seed_checklist_* (20260412131615–20260412132039)
-- 135 actionable compliance items across 10 regulations
-- Local reference copy of deployed seed data.

-- =============================================
-- GDPR (20 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-01', 'Identify lawful basis for each processing activity', 'Document the lawful basis (consent, contract, legal obligation, vital interests, public task, or legitimate interests) for every processing activity.', 'Use Article 6 analysis. Map each processing activity to one of the six lawful bases. Legitimate interests requires a balancing test (LIA).', 'Lawful Basis', 'critical', 'significant', 1),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-02', 'Create and maintain Record of Processing Activities (ROPA)', 'Maintain a written record of all processing activities as required by Article 30, including purposes, data categories, recipients, transfers, and retention periods.', 'Use a spreadsheet or dedicated tool. Must include: controller name, purposes, categories of data subjects and data, recipients, transfers to third countries, retention periods, and security measures.', 'Documentation', 'critical', 'significant', 2),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-03', 'Publish privacy notice for data subjects', 'Provide transparent information to data subjects about how their personal data is processed, per Articles 13-14.', 'Must cover: identity of controller, purposes, lawful basis, recipients, transfers, retention periods, data subject rights, and right to complain to Datatilsynet. Use plain language.', 'Transparency', 'critical', 'moderate', 3),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-04', 'Implement data subject access request (DSAR) procedure', 'Establish a documented process to handle access requests within one month, as required by Article 15.', 'Create a DSAR form, train staff to recognise requests, establish identity verification, and set up tracking to meet the one-month deadline (extendable by two months for complex requests).', 'Data Subject Rights', 'high', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-05', 'Implement right to erasure procedure', 'Enable data subjects to request deletion of their personal data under Article 17 conditions.', 'Document grounds for erasure and exceptions (legal obligations, public interest). Implement technical capability to delete across all systems including backups.', 'Data Subject Rights', 'high', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-06', 'Implement data portability procedure', 'Allow data subjects to receive their data in a structured, machine-readable format per Article 20.', 'Applies when processing is based on consent or contract and carried out by automated means. Implement JSON or CSV export functionality.', 'Data Subject Rights', 'medium', 'moderate', 6),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-07', 'Conduct Data Protection Impact Assessments (DPIAs)', 'Perform DPIAs for processing operations likely to result in high risk to individuals, per Article 35.', 'Required for: systematic profiling with legal effects, large-scale special category processing, systematic monitoring of public areas. Use Datatilsynet DPIA guidance template.', 'Risk Assessment', 'high', 'significant', 7),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-08', 'Appoint Data Protection Officer if required', 'Designate a DPO when processing is core activity involving regular/systematic monitoring at scale or large-scale special category data (Article 37).', 'DPO must have expert knowledge of data protection law, report to highest management, and operate independently. Can be internal or external. Publish DPO contact details and notify Datatilsynet.', 'Governance', 'high', 'significant', 8),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-09', 'Implement data breach notification procedure', 'Establish a process to detect, investigate, and report personal data breaches to Datatilsynet within 72 hours (Article 33) and to affected data subjects without undue delay when high risk (Article 34).', 'Create breach response plan, train staff on breach recognition, maintain breach register, prepare notification templates for Datatilsynet and data subjects.', 'Incident Response', 'critical', 'moderate', 9),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-10', 'Establish data processing agreements (DPAs) with all processors', 'Execute written agreements with all data processors per Article 28, covering processing instructions, confidentiality, security measures, sub-processing, and audit rights.', 'Review all vendors that process personal data on your behalf. Use Standard Contractual Clauses where applicable. Include provisions for data return/deletion on termination.', 'Third Parties', 'critical', 'moderate', 10),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-11', 'Implement appropriate technical security measures', 'Apply encryption, pseudonymisation, access controls, and other technical measures appropriate to the risk level (Article 32).', 'Minimum: encryption in transit (TLS) and at rest, role-based access control, MFA for admin access, regular vulnerability scanning, secure development practices.', 'Security', 'critical', 'significant', 11),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-12', 'Implement organisational security measures', 'Establish data protection policies, staff training, and internal controls.', 'Write and distribute a data protection policy. Conduct annual training for all staff. Implement clean desk policy. Define data classification scheme.', 'Security', 'high', 'moderate', 12),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-13', 'Ensure consent mechanisms meet GDPR requirements', 'Where consent is the lawful basis, ensure it is freely given, specific, informed, unambiguous, and as easy to withdraw as to give (Articles 7-8).', 'No pre-ticked boxes. Separate consent per purpose. Record when/how consent was given. Implement easy withdrawal mechanism. Children under 13 (DK) need parental consent for digital services.', 'Lawful Basis', 'high', 'moderate', 13),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-14', 'Implement data minimisation practices', 'Ensure only personal data that is necessary for each specific purpose is collected and processed (Article 5(1)(c)).', 'Audit current data collection forms and processes. Remove unnecessary fields. Implement mandatory field reviews for new projects. Document justification for each data element collected.', 'Data Quality', 'medium', 'moderate', 14),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-15', 'Define and enforce data retention periods', 'Establish retention schedules for all categories of personal data and implement automated or manual deletion when retention periods expire (Article 5(1)(e)).', 'Create retention schedule per data category. Implement automated purging where possible. Document legal hold procedures. Review annually.', 'Data Quality', 'high', 'moderate', 15),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-16', 'Conduct regular compliance audits', 'Perform periodic internal audits of data protection practices to identify gaps and ensure ongoing compliance.', 'Annual full audit recommended. Quarterly spot checks on high-risk processing. Document findings and remediation actions. Consider external audit every 2-3 years.', 'Governance', 'medium', 'moderate', 16),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-17', 'Train staff on data protection obligations', 'Provide regular data protection awareness training to all employees who handle personal data.', 'Onboarding training for new staff. Annual refresher for all. Role-specific training for IT, HR, marketing, and customer service. Document attendance.', 'Governance', 'high', 'minimal', 17),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-18', 'Implement privacy by design and default', 'Integrate data protection into the design of new systems, products, and processes from the outset (Article 25).', 'Include privacy review in project initiation. Default settings must be most privacy-friendly. Conduct privacy impact screening for all new projects.', 'Governance', 'medium', 'significant', 18),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-19', 'Document international data transfer mechanisms', 'Where personal data is transferred outside the EU/EEA, implement and document appropriate safeguards per Chapter V (Articles 44-49).', 'Map all international transfers. Use adequacy decisions, SCCs, or BCRs. Conduct Transfer Impact Assessments (TIAs). Monitor Datatilsynet guidance on Schrems II implications.', 'International Transfers', 'high', 'significant', 19),
((SELECT id FROM regulations WHERE slug = 'gdpr'), 'GDPR-20', 'Maintain data breach incident register', 'Keep a log of all personal data breaches regardless of whether they were reported to the authority (Article 33(5)).', 'Record: date of breach, nature, categories/numbers affected, consequences, remedial actions taken, notification decisions and dates. Review register quarterly.', 'Incident Response', 'high', 'minimal', 20);

-- =============================================
-- Databeskyttelsesloven (15 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-01', 'Comply with Danish CPR number processing restrictions', 'Danish civil registration numbers (CPR-numre) may only be processed when specifically authorised under Section 11 of the Act.', 'CPR numbers can be processed when required by law, for unambiguous identification, or with explicit consent. Never use CPR as general identifier. Implement technical controls to prevent unnecessary CPR collection.', 'CPR Numbers', 'critical', 'moderate', 1),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-02', 'Apply Danish age of consent rules for digital services', 'Children under 13 cannot consent to information society services. Parental consent required for children aged 13-17 in certain contexts (Section 6a).', 'Implement age verification for digital services. Obtain verifiable parental consent for under-13s. Document age-gating mechanisms.', 'Consent', 'high', 'moderate', 2),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-03', 'Follow Datatilsynet employee monitoring guidance', 'Employee monitoring (email, internet, GPS, video) must comply with Datatilsynet guidelines and Danish employment law.', 'Inform employees before monitoring begins. Document lawful basis (typically legitimate interest). Conduct balancing test. Limit monitoring to what is necessary. Follow the Datatilsynet guidance on workplace surveillance.', 'Employment', 'high', 'moderate', 3),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-04', 'Comply with video surveillance rules', 'TV-overvågningsloven governs CCTV use. Signage required. Datatilsynet registration may be needed. Footage retention limited to 30 days unless specific exception.', 'Post visible signage at all camera locations. Register with Datatilsynet if monitoring public areas. Delete footage after 30 days. Restrict access to recordings.', 'Surveillance', 'medium', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-05', 'Document lawful basis for processing criminal conviction data', 'Processing of criminal offence data requires specific authorisation under Section 8 — cannot rely solely on GDPR Article 6.', 'Map all processing of criminal data. Verify Danish legal basis exists. Limit access strictly. Consider whether processing is truly necessary.', 'Special Categories', 'high', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-06', 'Implement Datatilsynet minimum security requirements', 'Follow Datatilsynet''s published minimum technical and organisational security measures for personal data processing.', 'Implement: access control, logging, encryption, secure transmission, patch management, malware protection, backup procedures, physical security. Follow Datatilsynet''s "Measures of Security" guidance.', 'Security', 'critical', 'significant', 6),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-07', 'Report data breaches to Datatilsynet within 72 hours', 'Use Datatilsynet''s online breach notification form. Include all required information per their specific format.', 'Bookmark https://www.datatilsynet.dk/english/breach-notification. Prepare template responses. Train staff on Danish-specific notification requirements. Note that Datatilsynet may require Danish language submissions.', 'Incident Response', 'critical', 'minimal', 7),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-08', 'Follow Danish rules on automated individual decision-making', 'Sections 12-12b impose Danish-specific restrictions on solely automated decisions with legal or significant effects.', 'Identify all automated decision-making processes. Implement human review mechanism. Provide meaningful information about logic involved. Allow data subjects to contest decisions.', 'Automated Decisions', 'high', 'significant', 8),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-09', 'Maintain documentation in Danish for Datatilsynet', 'Key compliance documentation should be available in Danish for regulatory submissions and inspections.', 'Maintain Danish versions of: privacy policy, ROPA, breach procedures, DPA templates, internal policies. Ensure translations are legally accurate.', 'Documentation', 'medium', 'moderate', 9),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-10', 'Follow Datatilsynet cloud computing guidelines', 'Datatilsynet has specific guidance on cloud services including risk assessment requirements and data processor obligations.', 'Conduct risk assessment before cloud adoption. Ensure DPA covers cloud-specific risks. Verify data location. Assess sub-processor chains. Follow Datatilsynet''s cloud guidance document.', 'Third Parties', 'high', 'moderate', 10),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-11', 'Apply sector-specific codes of conduct', 'Follow any Datatilsynet-recognised codes of conduct applicable to your sector.', 'Check Datatilsynet website for approved codes of conduct. If your sector has one, document adherence. Consider joining sector associations that maintain codes.', 'Governance', 'low', 'minimal', 11),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-12', 'Register processing activities with Datatilsynet if required', 'Certain high-risk processing activities may require prior consultation with Datatilsynet per Section 25.', 'Review DPIA outcomes — if residual risk remains high, engage Datatilsynet prior consultation. Document all consultation interactions.', 'Governance', 'medium', 'moderate', 12),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-13', 'Handle Danish-specific consent restrictions in employment', 'In Danish employment context, consent is generally not valid as lawful basis due to power imbalance. Use alternative legal bases.', 'Do not rely on employee consent for processing employment data. Use legal obligation or legitimate interest instead. Document the balancing test for legitimate interest.', 'Employment', 'high', 'minimal', 13),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-14', 'Comply with Danish marketing law data requirements', 'Markedsføringsloven (Marketing Practices Act) intersects with data protection for direct marketing activities.', 'Obtain opt-in consent for electronic marketing to individuals. Maintain Robinson list checks for postal marketing. Separate marketing consent from other consents.', 'Marketing', 'medium', 'moderate', 14),
((SELECT id FROM regulations WHERE slug = 'databeskyttelsesloven'), 'DPA-15', 'Conduct annual data protection compliance review', 'Perform an annual review of data protection compliance aligned with Datatilsynet expectations and Danish regulatory developments.', 'Review changes to Datatilsynet guidance. Update ROPA and procedures. Check for new sector requirements. Document review findings and actions taken.', 'Governance', 'medium', 'moderate', 15);

-- =============================================
-- ePrivacy / Cookies (15 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-01', 'Implement cookie consent banner with granular controls', 'Display a consent banner that allows users to accept/reject cookies by category before non-essential cookies are set.', 'Use a CMP (Consent Management Platform) like Cookiebot or CookieYes. Must block non-essential cookies until consent is given. Provide granular category choices (necessary, functional, analytics, marketing).', 'Cookie Consent', 'critical', 'moderate', 1),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-02', 'Categorise all cookies and tracking technologies', 'Audit and classify every cookie and tracker into necessary, functional, analytics, and marketing categories.', 'Run a cookie scan tool. Document each cookie: name, provider, purpose, category, duration, type (first/third party). Update inventory when adding new tools or services.', 'Cookie Management', 'high', 'moderate', 2),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-03', 'Maintain a cookie register/inventory', 'Keep an up-to-date register of all cookies and similar technologies used across your digital properties.', 'Include: cookie name, domain, purpose, provider, category, expiry, first/third party. Review and update quarterly or when deploying new features.', 'Cookie Management', 'high', 'minimal', 3),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-04', 'Obtain explicit consent before setting non-essential cookies', 'No analytics, marketing, or functional cookies may be placed until the user has given affirmative consent.', 'Implement consent-gating in tag manager or CMP. Verify with browser DevTools that non-essential cookies are only set after consent. Test regularly.', 'Cookie Consent', 'critical', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-05', 'Provide mechanism to withdraw cookie consent', 'Users must be able to change or withdraw their cookie consent as easily as they gave it.', 'Add a persistent "Cookie Settings" link in the footer. Reopening the CMP banner must allow category-level changes. Withdrawal must actually delete the relevant cookies.', 'Cookie Consent', 'high', 'minimal', 5),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-06', 'Document cookie consent records', 'Maintain records of consent given by users as evidence of lawful cookie usage.', 'CMP should store: timestamp, user identifier (anonymised), consent version, categories consented to. Retain records for duration of processing. Be able to demonstrate consent if challenged.', 'Documentation', 'medium', 'minimal', 6),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-07', 'Review third-party cookies and tracking technologies', 'Audit all third-party scripts and trackers embedded in your digital services.', 'Inventory all third-party tags (analytics, ads, social embeds, chat widgets). Verify each has a lawful basis. Implement consent-gating for each. Check for undocumented tracking.', 'Third Parties', 'high', 'moderate', 7),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-08', 'Implement consent for email marketing (opt-in)', 'Electronic direct marketing to individuals requires prior opt-in consent under ePrivacy and Markedsføringsloven.', 'Implement double opt-in for marketing emails. Maintain subscriber consent records. Include unsubscribe link in every message. Process unsubscribes within 48 hours.', 'Email Marketing', 'critical', 'moderate', 8),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-09', 'Comply with telephone marketing restrictions', 'Respect the Danish Robinson list and do-not-call rules for telephone marketing.', 'Check Robinson list before B2C calls. Honour opt-out requests immediately. Do not call outside permitted hours. Maintain internal do-not-call list. Document compliance.', 'Telemarketing', 'medium', 'minimal', 9),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-10', 'Update cookie policy with clear descriptions', 'Publish a comprehensive cookie policy explaining what cookies are used, why, and how users can control them.', 'Plain language, no legalese. Cover: what cookies are, categories used, specific cookies per category, how to manage/delete, link to cookie settings, third-party cookie details.', 'Transparency', 'high', 'minimal', 10),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-11', 'Implement consent for mobile app tracking', 'Mobile apps must obtain consent before accessing device identifiers or setting tracking technologies.', 'Implement ATT (App Tracking Transparency) on iOS. Request consent before initialising analytics/ad SDKs on Android. Store consent preferences. Respect OS-level tracking settings.', 'Mobile', 'high', 'moderate', 11),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-12', 'Conduct regular cookie audits', 'Perform periodic scans to detect new, changed, or undocumented cookies on your digital properties.', 'Automated monthly scans recommended. Compare results against cookie register. Investigate any new/unknown cookies. Update CMP configuration. Document audit results.', 'Cookie Management', 'medium', 'minimal', 12),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-13', 'Ensure cookie lifetime compliance', 'Cookie durations should be proportionate to their purpose. Avoid excessively long cookie lifetimes.', 'Session cookies for temporary purposes. Analytics cookies: max 2 years (consider 13 months per CNIL guidance adopted by many DPAs). Marketing cookies: review necessity of duration.', 'Cookie Management', 'medium', 'minimal', 13),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-14', 'Implement server-side consent verification', 'Verify consent status server-side before processing data collected via cookies.', 'Do not rely solely on client-side consent checks. Pass consent signal to backend. Verify before processing analytics data. Implement consent-aware data pipelines.', 'Technical', 'medium', 'significant', 14),
((SELECT id FROM regulations WHERE slug = 'eprivacy'), 'EPRIV-15', 'Train marketing team on ePrivacy requirements', 'Ensure marketing and digital teams understand cookie consent and electronic marketing rules.', 'Cover: cookie categories, consent requirements, email opt-in rules, telemarketing restrictions, consequences of non-compliance. Provide practical checklists for campaign launch.', 'Training', 'medium', 'minimal', 15);

-- =============================================
-- NIS2 (15 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-01', 'Determine entity classification (essential/important)', 'Assess whether your organisation is an essential or important entity under NIS2 Annex I/II based on sector, size, and criticality.', 'Essential entities: large enterprises in Annex I sectors. Important entities: medium enterprises in Annex I or medium/large in Annex II. Size thresholds: 50+ employees or EUR 10M+ turnover.', 'Classification', 'critical', 'minimal', 1),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-02', 'Register with CFCS (Danish competent authority)', 'Register your entity with Center for Cybersikkerhed as required by the Danish NIS2 implementation.', 'Submit registration with: entity name, sector, contact details, IP ranges, and EU member states of operation. Update within 2 weeks of any changes.', 'Registration', 'critical', 'minimal', 2),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-03', 'Implement cybersecurity risk management framework', 'Establish an all-hazards approach to cybersecurity risk management covering policies, procedures, and technical controls (Article 21).', 'Adopt a recognised framework (ISO 27001, NIST CSF). Conduct risk assessments at least annually. Document risk appetite and treatment plans. Management body must approve the framework.', 'Risk Management', 'critical', 'significant', 3),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-04', 'Establish incident response and reporting procedures', 'Implement incident detection, handling, and mandatory reporting: early warning within 24h, incident notification within 72h, final report within 1 month (Article 23).', 'Create incident response plan with clear roles. Implement SIEM/monitoring. Prepare notification templates for CFCS. Conduct tabletop exercises quarterly.', 'Incident Response', 'critical', 'significant', 4),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-05', 'Implement supply chain security assessments', 'Assess and manage cybersecurity risks in your supply chain and supplier relationships (Article 21(2)(d)).', 'Inventory critical suppliers. Include cybersecurity requirements in contracts. Conduct supplier security assessments. Monitor for supply chain vulnerabilities. Review annually.', 'Supply Chain', 'high', 'significant', 5),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-06', 'Conduct vulnerability assessments and penetration testing', 'Perform regular vulnerability scanning and penetration testing to identify and remediate security weaknesses.', 'Automated vulnerability scanning monthly. Annual penetration testing by qualified third party. Remediate critical/high findings within 30 days. Track remediation metrics.', 'Testing', 'high', 'significant', 6),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-07', 'Implement business continuity and crisis management', 'Establish business continuity plans covering backup management, disaster recovery, and crisis management (Article 21(2)(c)).', 'Develop BCP and DRP. Test annually. Implement automated backups with regular restore testing. Define RTO/RPO for critical services. Establish crisis communication plan.', 'Resilience', 'high', 'significant', 7),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-08', 'Ensure management body cybersecurity training', 'Management body members must undergo cybersecurity training to oversee risk management measures (Article 20(2)). Personal liability applies.', 'Arrange annual cybersecurity training for board/management. Topics: threat landscape, risk management principles, regulatory obligations, personal liability under NIS2.', 'Governance', 'critical', 'minimal', 8),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-09', 'Implement multi-factor authentication and access management', 'Deploy MFA and zero-trust access controls for all critical systems and administrative access (Article 21(2)(j)).', 'Implement MFA for all privileged accounts and remote access. Adopt least-privilege principle. Review access rights quarterly. Implement PAM solution for admin accounts.', 'Access Control', 'high', 'moderate', 9),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-10', 'Deploy encryption and cryptography policies', 'Implement encryption policies covering data in transit, at rest, and cryptographic key management (Article 21(2)(h)).', 'TLS 1.2+ for all communications. AES-256 for data at rest. Implement key management procedures. Document cryptographic inventory. Phase out deprecated algorithms.', 'Security', 'high', 'moderate', 10),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-11', 'Implement network segmentation and monitoring', 'Segment networks to contain breaches and implement continuous monitoring for anomalous activity.', 'Separate IT/OT networks. Implement micro-segmentation for critical assets. Deploy IDS/IPS. Implement logging and SIEM. Monitor for lateral movement.', 'Security', 'high', 'significant', 11),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-12', 'Establish secure development practices', 'Implement security in software development lifecycle including vulnerability handling and disclosure (Article 21(2)(e)).', 'Adopt secure SDLC. Implement code review and SAST/DAST. Maintain vulnerability disclosure policy. Patch management within defined SLAs.', 'Development', 'medium', 'significant', 12),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-13', 'Conduct cybersecurity awareness training for all staff', 'Provide regular cybersecurity awareness training covering phishing, social engineering, password hygiene, and incident reporting.', 'Onboarding training for new hires. Quarterly phishing simulations. Annual comprehensive training. Track completion rates. Tailor content to roles.', 'Training', 'high', 'minimal', 13),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-14', 'Document and maintain asset inventory', 'Maintain a comprehensive inventory of all ICT assets, systems, and network components.', 'Catalogue all hardware, software, cloud services, and data assets. Include ownership, criticality classification, and dependencies. Update automatically where possible. Review quarterly.', 'Asset Management', 'high', 'moderate', 14),
((SELECT id FROM regulations WHERE slug = 'nis2'), 'NIS2-15', 'Implement patch management procedures', 'Establish systematic patch management covering identification, testing, deployment, and verification of security patches.', 'Monitor vendor advisories. Risk-based patching: critical within 48h, high within 7 days, medium within 30 days. Test patches before production deployment. Maintain patch compliance metrics.', 'Security', 'high', 'moderate', 15);

-- =============================================
-- EU AI Act (15 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-01', 'Inventory all AI systems in use', 'Create a comprehensive register of all AI systems developed, deployed, or used by your organisation.', 'Include: system name, provider, purpose, risk classification, deployment date, responsible team. Cover internal tools, vendor AI features, and embedded AI in SaaS products.', 'Inventory', 'critical', 'moderate', 1),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-02', 'Classify AI systems by risk category', 'Categorise each AI system as unacceptable risk (prohibited), high-risk, limited risk, or minimal risk per Annex III and Title II.', 'Prohibited: social scoring, real-time biometric ID in public (with exceptions), emotion recognition in workplace/education, manipulative AI. High-risk: see Annex III (HR, credit, law enforcement, etc.).', 'Classification', 'critical', 'moderate', 2),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-03', 'Cease use of prohibited AI practices', 'Identify and discontinue any AI systems classified as unacceptable risk under Article 5.', 'Review for: subliminal manipulation, exploitation of vulnerabilities, social scoring, real-time biometric identification (without legal basis), emotion inference in workplace/education, untargeted facial recognition scraping.', 'Prohibited Practices', 'critical', 'significant', 3),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-04', 'Implement transparency requirements', 'Ensure AI systems that interact with people are clearly identified as AI. Disclose AI-generated or manipulated content.', 'Label chatbots and virtual assistants as AI. Mark deepfakes and AI-generated content. Inform users when content recommendation is AI-driven. Document transparency measures.', 'Transparency', 'high', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-05', 'Conduct fundamental rights impact assessment for high-risk AI', 'Deployers of high-risk AI systems must assess the impact on fundamental rights before deployment (Article 27).', 'Assess impact on: non-discrimination, privacy, freedom of expression, human dignity, access to justice. Document mitigation measures. Consult affected stakeholders where appropriate.', 'Risk Assessment', 'high', 'significant', 5),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-06', 'Implement human oversight mechanisms for high-risk AI', 'High-risk AI systems must have appropriate human oversight to minimise risks (Article 14).', 'Define human-in-the-loop or human-on-the-loop procedures depending on risk. Ensure operators can interpret outputs, override decisions, and intervene. Document oversight procedures.', 'Human Oversight', 'critical', 'significant', 6),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-07', 'Establish AI governance framework', 'Create organisational structure and policies for responsible AI development and deployment.', 'Designate AI governance owner. Define AI ethics principles. Establish review process for new AI deployments. Create AI risk committee or integrate into existing risk management.', 'Governance', 'high', 'significant', 7),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-08', 'Maintain technical documentation for high-risk AI', 'High-risk AI providers must create and maintain comprehensive technical documentation per Annex IV.', 'Document: system description, design choices, training data, testing methodology, performance metrics, known limitations, risk management measures, changes log.', 'Documentation', 'high', 'significant', 8),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-09', 'Ensure training data quality and bias monitoring', 'High-risk AI training data must meet quality criteria including relevance, representativeness, and freedom from bias (Article 10).', 'Implement data governance for AI training sets. Monitor for statistical bias across protected characteristics. Document data provenance. Implement ongoing bias detection in production.', 'Data Quality', 'high', 'significant', 9),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-10', 'Implement logging and traceability for AI decisions', 'High-risk AI systems must automatically log events to enable traceability of system operation (Article 12).', 'Log: input data, outputs/decisions, confidence scores, human interventions, system errors. Retain logs per regulation requirements. Ensure logs support post-hoc auditing.', 'Logging', 'high', 'moderate', 10),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-11', 'Register high-risk AI systems in EU database', 'Providers and deployers of high-risk AI must register systems in the EU public database before market placement (Article 49).', 'Register at the EU AI database (when available). Include: provider details, system description, risk classification, conformity assessment reference. Update for material changes.', 'Registration', 'high', 'minimal', 11),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-12', 'Implement AI literacy training for staff', 'Ensure staff involved with AI systems have sufficient AI literacy appropriate to their role (Article 4).', 'Cover: what AI is, how your systems work, limitations, bias risks, ethical considerations, regulatory obligations. Role-specific depth: developers vs. operators vs. management.', 'Training', 'medium', 'moderate', 12),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-13', 'Establish post-market monitoring for deployed AI', 'Providers of high-risk AI must implement a post-market monitoring system proportionate to the AI system (Article 72).', 'Monitor: accuracy degradation, bias drift, user complaints, incident reports, edge cases. Define thresholds for remedial action. Report serious incidents to authority.', 'Monitoring', 'high', 'significant', 13),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-14', 'Implement incident reporting for AI malfunctions', 'Report serious incidents involving high-risk AI to the relevant market surveillance authority.', 'Define what constitutes a serious incident (death, serious health damage, fundamental rights violation, property/environment damage). Report without undue delay. Investigate root cause.', 'Incident Response', 'high', 'moderate', 14),
((SELECT id FROM regulations WHERE slug = 'ai_act'), 'AI-15', 'Ensure AI systems meet accuracy, robustness, and cybersecurity requirements', 'High-risk AI must achieve appropriate levels of accuracy, robustness, and cybersecurity throughout its lifecycle (Article 15).', 'Define and test accuracy metrics. Implement adversarial robustness testing. Secure AI pipeline (training data, model, inference). Protect against data poisoning and model extraction.', 'Technical', 'high', 'significant', 15);

-- =============================================
-- Bogforingsloven (15 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-01', 'Transition to approved digital bookkeeping system', 'Use a digital bookkeeping system registered and approved by Erhvervsstyrelsen.', 'Check Erhvervsstyrelsen''s list of approved systems. Major providers: e-conomic, Dinero, Billy. Ensure the system is registered before the compliance deadline for your company size.', 'System Requirements', 'critical', 'significant', 1),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-02', 'Ensure system meets Erhvervsstyrelsen technical requirements', 'Bookkeeping system must support automatic backup, audit trail, and standard export format.', 'Verify system provides: automatic time-stamping, sequential numbering, tamper-evident logging, automatic cloud backup, and SAF-T DK export capability.', 'System Requirements', 'critical', 'moderate', 2),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-03', 'Maintain digital records for minimum 5 years', 'All bookkeeping records must be stored digitally and retained for at least 5 years from the end of the financial year.', 'Configure retention policies in your system. Ensure backup retention matches. Include: receipts, invoices, bank statements, contracts, and supporting documentation.', 'Record Keeping', 'critical', 'moderate', 3),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-04', 'Implement automatic backup of bookkeeping data', 'Digital bookkeeping systems must perform automatic backup to a secure secondary location.', 'Verify your approved system handles this automatically. If self-hosted, implement daily encrypted backups to geographically separate location. Test restore procedures quarterly.', 'Data Protection', 'high', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-05', 'Ensure audit trail for all financial transactions', 'Every transaction must have a complete, unalterable audit trail from entry to financial statement.', 'Ensure system logs: who entered/modified each transaction, when, what was changed. No deletion of entries — corrections via reversal entries only.', 'Record Keeping', 'critical', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-06', 'Store bookkeeping data in approved format', 'Bookkeeping data must be stored in a format that allows Erhvervsstyrelsen to access and review records.', 'Use the system''s native storage. Ensure SAF-T DK export is functional. Test export regularly. Keep format documentation for any custom integrations.', 'System Requirements', 'high', 'minimal', 6),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-07', 'Implement access controls for financial records', 'Restrict access to bookkeeping data to authorised personnel with appropriate segregation of duties.', 'Define roles: bookkeeper, accountant, auditor, manager. Implement least-privilege access. Log all access to financial records. Review access rights semi-annually.', 'Security', 'high', 'moderate', 7),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-08', 'Ensure SAF-T DK export capability', 'System must be able to export data in the Danish Standard Audit File for Tax (SAF-T DK) format on demand.', 'SAF-T DK is XML-based. Test export annually. Verify completeness against Erhvervsstyrelsen specifications. Ensure export includes all required data fields.', 'Reporting', 'high', 'minimal', 8),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-09', 'Maintain bank reconciliation records digitally', 'Bank reconciliations must be performed regularly and stored as part of the digital bookkeeping records.', 'Reconcile bank accounts at least monthly. Use automatic bank feed integration where available. Store reconciliation reports digitally. Investigate and document all discrepancies.', 'Record Keeping', 'medium', 'minimal', 9),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-10', 'Document bookkeeping procedures and internal controls', 'Maintain written description of bookkeeping procedures, including who is responsible for what.', 'Document: chart of accounts, transaction recording procedures, approval workflows, reconciliation procedures, year-end closing process, and responsible persons.', 'Documentation', 'medium', 'moderate', 10),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-11', 'Comply with e-invoicing requirements', 'Implement electronic invoicing in compliance with Danish requirements for B2G and increasingly B2B transactions.', 'Support OIOUBL and/or PEPPOL BIS formats. Register in NemHandel if doing business with public sector. Ensure digital invoice storage as part of bookkeeping records.', 'Invoicing', 'medium', 'moderate', 11),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-12', 'Implement data retention policy for financial records', 'Define clear retention and destruction policies aligned with the 5-year minimum requirement.', 'Minimum 5 years from end of financial year. Some records require longer retention (tax disputes: 5+ years, real estate: 10 years). Implement automated archival. Document destruction procedures.', 'Record Keeping', 'medium', 'minimal', 12),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-13', 'Train staff on digital bookkeeping requirements', 'Ensure all personnel involved in bookkeeping understand the digital requirements and their responsibilities.', 'Training topics: approved system usage, proper transaction recording, document attachment procedures, audit trail maintenance, SAF-T export. Annual refresher recommended.', 'Training', 'medium', 'minimal', 13),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-14', 'Register bookkeeping system with Erhvervsstyrelsen', 'Confirm that your chosen bookkeeping system is registered with Erhvervsstyrelsen as an approved digital system.', 'Check registration at https://erhvervsstyrelsen.dk. If using a custom/in-house system, apply for registration. Monitor for any de-registration notices.', 'Registration', 'critical', 'minimal', 14),
((SELECT id FROM regulations WHERE slug = 'bogfoeringsloven'), 'BOG-15', 'Conduct annual review of bookkeeping system compliance', 'Perform an annual assessment that your bookkeeping practices and systems remain compliant with current requirements.', 'Review: system registration status, backup functionality, export capability, access controls, record completeness, retention compliance. Document findings and remediation actions.', 'Governance', 'medium', 'moderate', 15);

-- =============================================
-- Hvidvaskloven / AML (10 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-01', 'Conduct AML risk assessment', 'Perform a business-wide money laundering and terrorist financing risk assessment.', 'Assess: customer types, products/services, delivery channels, geographic exposure. Update annually or on material changes. Document methodology and findings.', 'Risk Assessment', 'critical', 'significant', 1),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-02', 'Implement customer due diligence (KYC) procedures', 'Establish identity verification and ongoing monitoring for all customers.', 'Verify identity using reliable documents. Identify beneficial owners (25%+ ownership). Understand purpose of business relationship. Apply risk-based approach to depth of checks.', 'KYC', 'critical', 'significant', 2),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-03', 'Register with Finanstilsynet if obligated entity', 'Register as an obligated entity with the Danish FSA if your business falls under Hvidvaskloven scope.', 'Check if your sector is covered (finance, legal, accounting, real estate, gambling, etc.). Submit registration. Appoint AML responsible person and compliance officer.', 'Registration', 'critical', 'minimal', 3),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-04', 'Implement suspicious transaction reporting', 'Establish procedures to detect, investigate, and report suspicious activities to Hvidvasksekretariatet (Danish FIU).', 'Train staff on red flags. Implement transaction monitoring. Report via goAML portal. Do not tip off the customer. Retain reporting records.', 'Reporting', 'critical', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-05', 'Maintain AML documentation and records for 5 years', 'Keep all KYC documents, transaction records, and investigation files for minimum 5 years after business relationship ends.', 'Store: ID copies, verification records, transaction history, risk assessments, suspicious activity reports, training records. Implement secure archival with controlled access.', 'Record Keeping', 'high', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-06', 'Train staff on AML obligations', 'Provide regular AML training to all relevant employees.', 'Cover: legal obligations, customer due diligence procedures, red flags, reporting procedures, consequences of non-compliance. Annual training. Document attendance.', 'Training', 'high', 'minimal', 6),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-07', 'Appoint AML compliance officer', 'Designate a qualified person responsible for AML compliance at management level.', 'Must have sufficient authority, resources, and access to information. Report directly to management. Register with Finanstilsynet. Ensure independence from business operations.', 'Governance', 'high', 'minimal', 7),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-08', 'Implement enhanced due diligence for high-risk customers', 'Apply intensified checks for PEPs, high-risk countries, complex structures, and unusual transactions.', 'Screen against PEP lists. Enhanced monitoring for high-risk relationships. Senior management approval for PEP relationships. More frequent reviews. Document enhanced measures applied.', 'KYC', 'high', 'moderate', 8),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-09', 'Screen customers against sanctions lists', 'Check all customers and beneficial owners against EU and Danish sanctions lists.', 'Screen at onboarding and ongoing (daily batch or real-time). Cover: EU consolidated list, Danish sanctions, UN sanctions. Implement fuzzy matching. Escalate hits immediately.', 'Sanctions', 'critical', 'moderate', 9),
((SELECT id FROM regulations WHERE slug = 'hvidvaskloven'), 'AML-10', 'Conduct regular AML compliance reviews', 'Perform periodic internal reviews of AML programme effectiveness.', 'Annual self-assessment against Finanstilsynet guidelines. Test sample of KYC files. Review transaction monitoring effectiveness. Update risk assessment. Document findings and remediation.', 'Governance', 'medium', 'moderate', 10);

-- =============================================
-- Whistleblower Act (10 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-01', 'Establish internal whistleblower reporting channel', 'Set up a secure, confidential channel for employees to report breaches of EU or Danish law.', 'Can be digital platform, dedicated email, phone hotline, or physical mailbox. Must ensure confidentiality. Consider third-party platform for independence. Must be accessible to all employees.', 'Reporting Channel', 'critical', 'moderate', 1),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-02', 'Appoint impartial person/unit to handle reports', 'Designate a competent, independent person or unit to receive and follow up on whistleblower reports.', 'Can be internal (e.g., compliance officer, legal counsel) or external (law firm, service provider). Must be impartial and free from conflicts of interest. Ensure backup/deputy.', 'Governance', 'critical', 'moderate', 2),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-03', 'Acknowledge receipt of reports within 7 days', 'Confirm to the whistleblower that their report has been received within 7 calendar days.', 'Implement automated acknowledgment where possible. Include: confirmation of receipt, explanation of next steps, timeline for feedback. Maintain confidentiality in all communications.', 'Procedures', 'high', 'minimal', 3),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-04', 'Provide feedback to whistleblower within 3 months', 'Give the whistleblower feedback on actions taken or planned within 3 months of acknowledgment.', 'Feedback should cover: investigation status, actions taken or planned, outcome (if concluded). Balance transparency with confidentiality of third parties. Document feedback provided.', 'Procedures', 'high', 'minimal', 4),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-05', 'Protect whistleblower identity and ensure confidentiality', 'Implement technical and organisational measures to protect the identity of reporting persons.', 'Restrict access to report contents. Use secure communication channels. Anonymise data in investigations where possible. Log all access to reports. GDPR applies to personal data in reports.', 'Confidentiality', 'critical', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-06', 'Implement non-retaliation policy', 'Establish and enforce a policy prohibiting retaliation against whistleblowers.', 'Cover: dismissal, demotion, harassment, discrimination, withholding of promotion, transfer, negative performance review. Apply to whistleblower and facilitators. Reverse burden of proof for alleged retaliation.', 'Protection', 'critical', 'minimal', 6),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-07', 'Train employees on whistleblower procedures', 'Inform all employees about the existence and use of the whistleblower channel.', 'Cover: what can be reported, how to report, confidentiality guarantees, non-retaliation protection, external reporting options. Include in onboarding. Annual reminders.', 'Training', 'high', 'minimal', 7),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-08', 'Maintain records of reports for appropriate period', 'Keep secure records of all reports received, investigations conducted, and outcomes.', 'Retain records for duration required to fulfil legal obligations. GDPR data minimisation applies. Secure storage with restricted access. Delete when no longer legally required.', 'Record Keeping', 'medium', 'minimal', 8),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-09', 'Publish whistleblower policy to all employees', 'Make the whistleblower policy and reporting procedures easily accessible to all employees.', 'Publish on intranet, include in employee handbook, display in common areas. Provide in relevant languages. Update for any procedural changes. Include external reporting options (Datatilsynet, sector authorities).', 'Communication', 'high', 'minimal', 9),
((SELECT id FROM regulations WHERE slug = 'whistleblower'), 'WB-10', 'Conduct annual review of whistleblower system', 'Review the effectiveness and compliance of the whistleblower system annually.', 'Assess: channel accessibility, handling timeliness, confidentiality measures, non-retaliation compliance, staff awareness. Document review and improvements. Report to management.', 'Governance', 'medium', 'moderate', 10);

-- =============================================
-- PSD2 (10 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-01', 'Implement Strong Customer Authentication (SCA)', 'Apply SCA using two or more independent factors (knowledge, possession, inherence) for electronic payment transactions.', 'SCA required for: online payments, electronic remote payments, accessing payment accounts online. Exemptions available for low-value, trusted beneficiaries, recurring transactions. Implement 3DS2 for card payments.', 'Authentication', 'critical', 'significant', 1),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-02', 'Ensure PSD2-compliant API access for third-party providers', 'Provide dedicated APIs for licensed AISPs and PISPs to access payment accounts with customer consent.', 'APIs must meet RTS performance standards. Provide testing sandbox. Support OAuth 2.0 / OpenID Connect. Monitor API availability (99.5%+ uptime). Fall-back mechanism if dedicated interface fails.', 'Open Banking', 'high', 'significant', 2),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-03', 'Implement transaction monitoring for fraud detection', 'Deploy real-time transaction monitoring to detect and prevent fraudulent payment transactions.', 'Implement risk-based approach considering: transaction amount, known fraud patterns, unusual spending, device fingerprinting, geo-location. Define alert thresholds. Review flagged transactions within SLA.', 'Fraud Prevention', 'critical', 'significant', 3),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-04', 'Maintain PSD2 compliance documentation', 'Document all PSD2 compliance measures, risk assessments, and incident reports for Finanstilsynet.', 'Maintain: SCA implementation details, exemption usage records, fraud statistics, API performance logs, incident reports, risk assessments. Ready for regulatory inspection.', 'Documentation', 'medium', 'moderate', 4),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-05', 'Implement secure communication channels', 'Ensure all payment-related communications use secure, encrypted channels.', 'TLS 1.2+ for all APIs. Certificate-based mutual authentication (eIDAS certificates). Encrypt sensitive payment data at rest. Implement message-level signing where required.', 'Security', 'high', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-06', 'Conduct regular PSD2 security assessments', 'Perform periodic security testing of payment systems and APIs.', 'Annual penetration testing. Quarterly vulnerability scanning. Test SCA implementation. Review fraud monitoring effectiveness. Report results to Finanstilsynet as required.', 'Testing', 'high', 'significant', 6),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-07', 'Train staff on payment services regulations', 'Ensure relevant staff understand PSD2 obligations and operational procedures.', 'Cover: SCA requirements, fraud indicators, customer rights (refunds, liability), TPP access rules, incident reporting. Role-specific training for operations, IT, and compliance teams.', 'Training', 'medium', 'minimal', 7),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-08', 'Implement customer notification for unauthorised transactions', 'Notify customers immediately of suspected unauthorised transactions and process refunds per PSD2 timelines.', 'Customer liability capped at EUR 50 for unauthorised transactions (unless gross negligence). Refund within 1 business day of becoming aware. Investigate and communicate outcome within 15 business days.', 'Customer Rights', 'high', 'moderate', 8),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-09', 'Maintain incident reporting procedures for payment security', 'Establish process to report major operational or security incidents to Finanstilsynet.', 'Classify incidents by impact. Report major incidents within 4 hours. Submit intermediate report within 3 business days. Final report within 2 weeks. Use EBA classification guidelines.', 'Incident Response', 'critical', 'moderate', 9),
((SELECT id FROM regulations WHERE slug = 'psd2'), 'PSD2-10', 'Review and update payment service agreements', 'Ensure customer agreements and terms meet PSD2 transparency and information requirements.', 'Include: fee transparency, execution times, liability rules, complaint procedures, right to terminate. Provide in durable medium. Notify customers of changes with 2 months notice.', 'Contracts', 'medium', 'moderate', 10);

-- =============================================
-- DORA (10 items)
-- =============================================
INSERT INTO checklist_items (regulation_id, code, title, description, guidance, category, priority, effort_level, display_order)
VALUES
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-01', 'Establish ICT risk management framework', 'Implement a comprehensive framework for identifying, protecting against, detecting, responding to, and recovering from ICT risks (Article 6).', 'Adopt proportionate approach based on size and risk profile. Management body must define, approve, oversee, and be accountable for the framework. Align with ESA technical standards. Review annually.', 'Risk Management', 'critical', 'significant', 1),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-02', 'Implement ICT incident classification and reporting', 'Classify ICT incidents by severity and report major incidents to Finanstilsynet per DORA timelines (Article 19).', 'Initial notification within 4 hours of classification. Intermediate report within 72 hours. Final report within 1 month. Use ESA classification criteria (clients affected, duration, geographic spread, data loss, economic impact).', 'Incident Response', 'critical', 'significant', 2),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-03', 'Conduct digital operational resilience testing', 'Perform regular testing including vulnerability assessments, network security, and for significant entities: threat-led penetration testing (TLPT) per Article 26.', 'Annual basic testing for all. TLPT every 3 years for significant entities (using TIBER-EU or equivalent). Test critical systems and functions. Remediate findings with documented action plans.', 'Testing', 'high', 'significant', 3),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-04', 'Assess and monitor ICT third-party risks', 'Identify, assess, and continuously monitor risks from ICT third-party service providers (Chapter V).', 'Maintain register of all ICT TPP arrangements. Risk-assess before contracting. Include key contractual provisions (security, audit rights, exit strategy). Monitor concentration risk. Report critical TPPs to regulator.', 'Third Party Risk', 'critical', 'significant', 4),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-05', 'Implement information sharing on cyber threats', 'Participate in voluntary cyber threat intelligence sharing with other financial entities and authorities (Article 45).', 'Join relevant ISACs (Information Sharing and Analysis Centres). Share anonymised threat intelligence. Implement processes to receive and act on shared intelligence. Document sharing activities.', 'Threat Intelligence', 'medium', 'moderate', 5),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-06', 'Document ICT asset inventory and dependencies', 'Maintain a comprehensive inventory of ICT assets, systems, and their interconnections and dependencies.', 'Catalogue: hardware, software, cloud services, network components, data stores. Map dependencies and single points of failure. Classify by criticality. Update continuously. Include third-party provided assets.', 'Asset Management', 'high', 'moderate', 6),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-07', 'Implement business continuity for ICT services', 'Establish ICT business continuity policy and disaster recovery plans with defined RTO/RPO for critical functions (Article 11).', 'BIA for all ICT services. Defined RTO/RPO for critical/important functions. Implement redundancy. Test recovery annually. Scenario-based testing including cyber-attack scenarios. Communication plans for disruption.', 'Resilience', 'critical', 'significant', 7),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-08', 'Conduct regular scenario-based testing', 'Perform scenario-based testing covering plausible ICT disruption scenarios including cyber attacks.', 'Test scenarios: ransomware, DDoS, cloud provider failure, insider threat, supply chain compromise. Involve business and IT. Document outcomes. Integrate lessons learned into framework.', 'Testing', 'high', 'significant', 8),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-09', 'Establish oversight of critical ICT third-party providers', 'For critical ICT TPPs identified by ESAs, implement enhanced monitoring and contractual safeguards.', 'Ensure contracts include: full service descriptions, data location, security measures, audit rights, termination and transition clauses, sub-contracting controls. Participate in oversight framework. Develop exit strategies.', 'Third Party Risk', 'high', 'significant', 9),
((SELECT id FROM regulations WHERE slug = 'dora'), 'DORA-10', 'Train management on digital operational resilience', 'Ensure management body members maintain sufficient knowledge of ICT risks and DORA obligations.', 'Regular training on: ICT risk landscape, DORA requirements, incident response roles, personal accountability. Management must actively oversee ICT risk management. Document training completion.', 'Governance', 'high', 'minimal', 10);
